### ISSUE TITLE
Unnecessary code about _wait_lock() when shareable is true

### ISSUE THREAD

**Issue by lsj9383** [WebwareForPython/DBUtils#11]
```py
def connection(self, shareable=True):
    if shareable and self._maxshared:
        self._lock.acquire()
        try:
            while (not self._shared_cache and self._maxconnections
                    and self._connections >= self._maxconnections):
                >>> self._wait_lock() <<<
    ....
```
The code `self._wait_lock()` won't execute, because `_connections > 0` lead to `_shared_cache` not empty

**Comment by Cito** [comment]
Thanks for contributing. I believe this code is for the situation when all connections are used up with dedicated connections - two tests are failing when you remove this.

**Comment by lsj9383** [comment]
Thanks, you are right, I ignore the case
