### ISSUE TITLE
Still got OperationalError when using PersistentDB

### ISSUE THREAD

**Issue by yifeikong** [WebwareForPython/DBUtils#14]
```
conn = PersistentDB(
    mysql,
    ping=0,  # ping may cause segmentation fault
    host=os.getenv("VS_DB_HOST"),
    user=os.getenv("VS_DB_USER"),
    passwd=os.getenv("VS_DB_PASSWORD"),
    db=os.getenv("VS_DB_NAME"),
    charset="utf8mb4",
)
```

**Comment by yifeikong** [comment]
thanks, here are the details:

OS: Ubuntu 16.04
Python: CPython 3.6.5
Mysql Version: 8.0
DB Api: mysqlclient==1.3.13

I have a long runing script that uses DBUtils, after about 3 days, this error shows.

**Comment by yifeikong** [comment]
Thanks for your comments, I will try the new version and give feedback later.

**Comment by yifeikong** [comment]
Sorry, but mysqlclient=1.3.14 still not fix my problem. I'll try to post a full stack trace next time

**Comment by Cito** [comment]
The segfault you mention in the comment must actually be a driver problem, since DBUtils is pure Python.

For the OperationalError, it will help if you send a stack trace to find where it's originating and possible causes, if you can't provide a full reproducable test case.
