### ISSUE TITLE
Transactions getting rolled back, even after committing in PooledDb connection

### ISSUE THREAD

**Issue by kasturichavan** [WebwareForPython/DBUtils#17]
Creating two connection pools engines:-
1) For where all the transactions on the connection will be `autocommitted`
2) Where all the transactions on various connections will be be manually committed.
Creator used here is pyodbc.
Even after not sending the  "autocommit", the transactions that are manually committed while writing to DB are getting rolled back when closing the application.
Below mentioned code pattern was followed taking into consideration issue with pyodbc mentioned here https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management
But seems like the DbUtils PooledDB connection isnt sending right information to pyodbc. 

```
if autocommit_flag:    
                args: dict = {
                "autocommit": True,
                "Driver": "{ODBC Driver 11 for SQL Server}",
                "Server": xxxxx,
                "Database": xxxxxxx,
               "Uid": xxxxxxxx,
               "Pwd": xxxxxxx,
            }
            self._connection_pools_for_transactions_autocommitted[dbcode] = PooledDB(
                creator=pyodbc,
                mincached=1,
                maxcached=5,
                maxshared=5,
                maxusage=0,
                **args,
            )
        else:
          args: dict = {
                "Driver": "{ODBC Driver 11 for SQL Server}",
                "Server": xxxxx,
                "Database": xxxxxxx,
               "Uid": xxxxxxxx,
               "Pwd": xxxxxxx,
            }
            self._connection_pools_for_transactions_explicitly_committed[dbcode] = PooledDB(
                creator=pyodbc,
                mincached=1,
                maxcached=5,
                maxshared=5,
                maxusage=0,
                **args,
            )
```

```
def write(
        self,
        dbcode: str,
        sql: str,
        commit: bool = False,
        dedicated: bool = False,
        quiet: bool = False,
    ) -> bool:
        """Wraps the connect and execute steps for DB querys. Executes only one statement at a time

            Args:
                dbcode (str)               : The Database to run this query on
                sql (str)                  : The SQL query we want to execute
                commit (bool, optional)    : If we want to explicitly commit after execution
                dedicated (bool, optional) : If we want a seperate non-shared connection for executing the query
                quiet (bool, optional)     : If we should suppress exceptions
        """

        results: bool = False

        with self.get_cursor(dbcode, dedicated) as (cursor, connection):
            try:

                # begin transaction
                if commit:
                    cursor.execute("BEGIN TRANSACTION")

                # execute sql
                cursor.execute(sql)

                # determine if rows were affected
                if cursor.rowcount > 0:
                    results = True

            except pyodbc.Error as e:
                # rollback execution in response to error
                connection.rollback()
               if not quiet:
                    raise

            finally:

                # end transaction
                if commit:
                    connection.commit()

        return results
```

```
def _get_connection(self, dbcode: str, autocommit_flag: bool = True, dedicated_connection: bool = False):
        """Gets a connection from the pool of connections created for the specific database server

            Args:
                dbcode (str)                          : The database server whose connection is requested
                autocommit_flag (bool) : This flag determines if pyodbc connection handles autocommit of sql statements
                dedicated_connection (bool, optional) : Indicates if dedicated (non shared) connection for autocommited transactions
                                             is required for executing query

            Returns:
                object : A Pooled Shared DB Connection object

        """
        if autocommit_flag:
            if dbcode not in self._connection_pools_for_transactions_autocommitted:
                connection_creator = pyodbc
                connection_creator.pooling = False
                self._create_connection_pool(dbcode, connection_creator, autocommit_flag)

            pool = self._connection_pools_for_transactions_autocommitted[dbcode]
            return pool.dedicated_connection() if dedicated_connection else pool.connection()
        else:
            if dbcode not in self._connection_pools_for_transactions_explicitly_committed:
                connection_creator = pyodbc
                connection_creator.pooling = False
                self._create_connection_pool(dbcode, connection_creator, autocommit_flag)

            pool = self._connection_pools_for_transactions_explicitly_committed[dbcode]
            return pool.dedicated_connection()

```

**Comment by Cito** [comment]
1. In the first code snippet, which is the problematic case for you, with autocommit or without? Or both? 
2. In the function for the second one, do you set commit=True or not? It would only make sense in autocommit mode when you want to wrap several commands in a transaction.

Maybe you can send a complete executable example for me to reproduce? The type of database might also be important to know.

**Comment by kasturichavan** [comment]
The problem , is when we make a call to our db_provider to explicitly commit a transaction. In this case we use a connection from `_connection_pools_for_transactions_explicitly_committed `  dictionary of connections.
self.db_provider.write(db_code, sql, commit=True)

**Comment by Cito** [comment]
One problem I notice is that you start the transaction with `cursor.execute("BEGIN TRANSACTION")`. In DBUtils you should use `connection.begin()` instead to let DBUtils know about it. Otherwise you could maybe start a nested transaction (which SQL Server supports), and you commit only the inner one. Can you change that and see if it makes a difference?

**Comment by kasturichavan** [comment]
Sure trying now.

**Comment by kasturichavan** [comment]
That works. Thanks a lot. 💯 

Few questions about this change:
1) Based on snippet here in docs for PooledDB https://cito.github.io/DBUtils/UsersGuide.html#pooleddb
``` 
Note that you need to explicitly start transactions by calling the begin() method. This ensures that the connection will not be shared with other threads, that the transparent reopening will be suspended until the end of the transaction, and that the connection will be rolled back before being given back to the connection pool.
```
Based on your recommendation to use `connection.begin()` , does this mean that the sql statement run on this connection will always be run as dedicated even if the connection had maxShared > 0. 
So does this mean in snippet 3 when we try to retrieve the connection we dont need to make an effort of pool. dedicated_connection() ? Because pool.connection() and the connection.begin() is equivalent to pool.dedicated_connection()

**Comment by Cito** [comment]
Yes, from the time you call `connection.begin()` until the `commit()` or `rollback()` the connection is locked for other threads, even if it's not a dedicated connection. If you don't start a connection and only run select queries, the same connection could be used by other threads as well if it's not a dedicated one.

**Comment by kasturichavan** [comment]
Makes sense. There is no other way to run non-autocommitted queries and still have connection unblocked in DbUtils right ?

**Comment by Cito** [comment]
Yes. A transaction should be isolated, that's why DBUtils makes sure no other thread put its oar in while the transaction is running. Best practice for DBUtils is to encapsulate only the critical parts of the code where you're changing the database in transactions. When you're only querying the database, you don't need transactions and the connections can be shared freely.

You can also consider using PersistentDB instead of PooledDB - the user's guide explains the differences.

**Comment by kasturichavan** [comment]
Can you elaborate on this `when the connection is outside the transaction,` ? Will this help us run multiple queries/transactions which wrap many statements simultaneously on a pooled connection without blocking a connection.

**Comment by Cito** [comment]
I meant that you should only wrap the parts where you really need a transaction between begin() and end(). In the time before the begin() and after the end(), while you are just querying or processing data, the same connection can be used by other threads.

**Comment by kasturichavan** [comment]
We dont do begin() and end(), we use begin() and then eventually connection.close(). Should we be using  end() for explicit transactions on connection. 
Also if you have used sqlalchemy that works for threadedapplications as it uses scoped_session concept for threads.

**Comment by Cito** [comment]
Sorry, when I wrote end() I actually meant commit(). You nead that explicit commit(). But you're doing it already in the code above.

If you use SQLAlchemy, you won't need DBUtils, as it comes with its own connection pool. The SQLAlchemy sessions are thread local. I.e. the session and the underlying connection will not be used by other threads. Same as dedicated connections in DBUtils.
