### ISSUE TITLE
PooledDbconnection concerns temptables, FlaskApp

### ISSUE THREAD

**Issue by kasturichavan** [WebwareForPython/DBUtils#19]
Issue/Concerns:
- Temptables tempdb.dbo.#temp_table_name created in a  read request using PooledDbConnection, does not get deleted, after connection.close()
Whats the concept of session & connection in PooledDB context ?  
Temptables with `#` as prefix created ideally should get deleted when session ends. 
**Can someone help understand how the session and connection & transaction works in connection to pooledDB ?** 
- Should PooledDB instance we stored as a global  in flask Application ? Or will every request create a new pooledDb instance ? 

- Our MaxShared for pooledDb should match how many requests we aim to serve in our application at a given time. Let me know if im not understanding this correctly. 
Whats the goal of having maxCached ?

**Comment by kasturichavan** [comment]
Hi @Cito,
Thanks for detailed explanation. 
Follow up questions:
1>  If there is only one session per connection in pooledDB as explained above. And in connection pool this session is shared by all threads for reads . Then how are we able to read multiple result sets in one session?? 
Mutiple Active Result Set denotes multiple session on single connection right ?https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?redirectedfrom=MSDN&view=sql-server-2017
2> You mentioned use of begin() & end() , we are using (BEGIN TRAN, COMMIT, ROLLBACK) not using end(). Let me know if that not right.

**Comment by Cito** [comment]
1.+3. Mutiple Active Result Sets are not supported by DB-API 2, and consequently not by DBUtils.
2. Right, I meant commit() instead of end(). But you need begin() and commit/rollback() calls so that DBUtils knows you're in a transaction, not something like execute('BEGIN TRANS').
4. These are internal attributes/methods to support the setsession parameter. In this parameter you can pass a list of SQL commands that are executed once after a new connection is created.

**Comment by kasturichavan** [comment]
Gotcha. Makes sense. for 2 & 3.
For 1> If MARS is not supported by DB-API2 then how are we able to run multiple reads on shared pooledDB connection? Since one connection only has one session.

**Comment by Cito** [comment]
Not sure if I understand your question. In DB-API 2 you have cursors. Each thread creates their own cursors. The cursors are private to the threads. You execute queries and fetch results using the cursor.
