### ISSUE TITLE
Please update pypi release

### ISSUE THREAD

**Issue by meteormatt** [WebwareForPython/DBUtils#25]
https://pypi.org/project/DBUtils/ still can not support Python 3.8

**Comment by Cito** [comment]
A new release is on my to do list already. 

If you noticed anything in the current master that's broken with Python 3.8 in the current master let me know. The tests seem to run, I only get a deprecation warning (#26).

**Comment by Cito** [comment]
Versions 1.4 and 2.0 have now been released to PyPI. They support Python 3.8 and 3.9.

Starting from version 2.0, DBUtils is now a normal package only and does not act as a Webware for Python plugin anymore.
