### ISSUE TITLE
Request to add import module name compatible with 1.x version in v2.x version

### ISSUE THREAD

**Issue by YongJie-Xie** [WebwareForPython/DBUtils#27]
1.x
from DBUtils.PooledDB import PooledDB
2.x
from dbutils.pooled_db import PooledDB

I hope that the module name of the imported module can be compatible with the 1.x version in the 2.x version, and add a warning message when using the compatibility import.

Thx : )

**Comment by Cito** [comment]
We would need to install another top-level package DBUtils which I want to avoid.

I think it's ok to require that little change from users. That's why I released it with a new version number.

**Comment by YongJie-Xie** [comment]
Ok, fine. I think you need to put this message in a more conspicuous place in the docs.

**Comment by Cito** [comment]
Ok, I have highlighted the breaking changes and link to the changelog on the README page now.
