### ISSUE TITLE
[RFE] Can wheels for DBUtils be placed up on pypi?

### ISSUE THREAD

**Issue by jcpunk** [WebwareForPython/DBUtils#29]
Would it be possible to start building wheels for DBUtils for hosting on pypi?

**Comment by Cito** [comment]
Yes, I wanted to automate the PyPI releases anyway (#30). It's on my todo list.

**Comment by Cito** [comment]
Version 2.0.1 has now been released with wheels, and we now have a GitHub workflow for this.
