### ISSUE TITLE
Is there a way to set CLIENT_MULTI_STATEMENTS with PooledDB using the PyMySQL driver?

### ISSUE THREAD

**Issue by cryog0at** [WebwareForPython/DBUtils#32]
Hello,
I've been trying to enable the [CLIENT_MULTI_STATEMENTS](https://dev.mysql.com/doc/internals/en/capability-flags.html#flag-CLIENT_MULTI_STATEMENTS) flag with PooledDB using the PyMySQL driver. I've tried all sorts of syntax on connection with the "setsession" parameter with no luck, and at this point I'm wondering if it's even possible. Otherwise, I love this module, thank you for the work you do.

**Comment by Cito** [comment]
I'm a bit ignorant about MySQL because I prefer PostgreSQL. Are you sure these "capablity flags" can be even set on the SQL level? To me it looks like they are used on the client/server protocol level only. That would be something you need to configure in your MySQL driver then. Maybe you can do it by passing additional parameters when creating the PooledDB instance which will be forwarded to the connection function of the MySQL Python adapter you are using, or by using a creator function. You need to look up the documentation of that module.

**Comment by cryog0at** [comment]
No problem, I'm a bit ignorant about databases in general :)

I'm able to set this flag using regular pymysql using the following, so I assume there must be some sort of sql command or at least a flag being passed in the connection logic.

`
import pymysql
from pymysql.constants.CLIENT import MULTI_STATEMENTS
connection = pymysql.connect(host='localhost',
                             user='admin',
                             password='password',
                             db='mysql',
                             client_flag=MULTI_STATEMENTS)
`

Is there a way for me to configure driver-specific options when setting up the PooledDB connection?

**Comment by Cito** [comment]
Yes, that's what I mean. I think you can pass the `client_flag` as additional parameter when creating the PooledDB instance. It will then be passed on to `pymysql.connect` whenever PooledDB is creating a connection.

**Comment by cryog0at** [comment]
ok so let me see if I understand what you're saying. 

I'm currently creating my pooleddb instance similar to the following
```
pool = PooledDB(pymysql,5,host='ip',user='user',passwd='passwd',db='db',port=3306,setsession=['SET AUTOCOMMIT = 1'])
```

are you saying I should try something like this?
```
pool = PooledDB(pymysql,5,host='ip',user='user',passwd='passwd',db='db',port=3306,setsession=['SET AUTOCOMMIT = 1'], client_flag=MULTI_STATEMENTS)
```

**Comment by Cito** [comment]
Exactly. And I think you can also send autocommit as additional parameter `autocommit=True` instead of using `setsession`.

**Comment by cryog0at** [comment]
It worked! Thank you for your help
