### ISSUE TITLE
TCP connection disconnected problem

### ISSUE THREAD

**Issue by Holy-Shine** [WebwareForPython/DBUtils#34]
Hi,
At first thanks for your team for providing this useful database tool.
I have a problem in a specific situation:

- **I run my mysql management code in a docker container in a docker platform.**
- **This platform has a feature: when the idle time of a TCP connection in a running containner exceeds 240 seconds, it will be cut.**
- **This problem makes me unable to use PooledDB's database pool to access my mysql database. (when I take a connection from sql pool and execute a sql statement, I get a timeout error)**

I wonder if there is any PooledDB interface can solve this problem.

environment:
python3.9+DBUtils2.0.2+pymysql0.10.0

Thanks.

**Comment by Cito** [comment]
Sorry, there is no option for time-based refresh of connections as you may have hoped.

However, the SteadyDB connections that are used by DBUtils under the hood *should* recognize when they are cut off and transparently re-establish the connection. If this does not work, maybe there is a problem with MySQL or pymysql version - maybe pymysql is raising an exception that is not expected, caught and handled by DBUtils. You may want to experiment with the "ping" and "failures" parameters to check that out. 

Note that I'm using and testing DBUtils only with PostgreSQL, so I cannot help much with MySQL - personally, I don't understand why everybody always wants to use MySQL. If you find the cause and you can fix it, I will gladly receive pull requests.

Also, you should really try to switch off that "feature" that cuts off database connections. It calls for trouble even if you get it solved.
