### ISSUE TITLE
Connection won't reconnect if PostgreSQL server restarted

### ISSUE THREAD

**Issue by crvv** [WebwareForPython/DBUtils#36]
```Python
import random
import threading
import time
import traceback

import psycopg2
from dbutils.pooled_db import PooledDB

pool = PooledDB(
    psycopg2,
    # failures=(psycopg2.InterfaceError, psycopg2.OperationalError, psycopg2.InternalError),
    host='localhost',
)


def w():
    while True:
        try:
            with pool.connection() as db:
                with db.cursor() as cursor:
                    cursor.execute("select 1")
                    print(cursor.fetchall())
                db.commit()
        except Exception:
            traceback.print_exc()
        time.sleep(random.random())


for _ in range(10):
    t = threading.Thread(target=w)
    t.start()
```

Run this code. It prints lots of `[(1,)]`. Then restart PostgreSQL.
I got many `psycopg2.InterfaceError: connection already closed` error and it won't recover.

Maybe `InterfaceError` should be in the default value of `failures`.

**Comment by Cito** [comment]
Hi @crvv - thanks for reporting this. I agree that it would be good to add `InterfaceError`. Psycopg2 is a widely used adapter, which should be supported out of the box (besides the special support for PyGreSQL). Will create a patch release 3.0.1 with this change.

**Comment by Cito** [comment]
Version 3.0.1 is now available [on PyPI](https://pypi.org/project/DBUtils/3.0.1/).
