### ISSUE TITLE
SteadyDBCursor is not iterable

### ISSUE THREAD

**Issue by DasCapschen** [WebwareForPython/DBUtils#38]
SteadyDBCursor cannot be iterated, while pymysql's cursor does support iterating.

Is there any good reason why iteration is not implemented, or was this simply forgotten?

Pymysql seems to implement iteration like this. Could something like this be added?
```py
    def __iter__(self):
        return iter(self.fetchone, None)
```

**Comment by Cito** [comment]
Thanks for reporting, @DasCapschen. Probably an oversight, as iteration is only an optional extension, not part of the base spec.

Can you check whether the above commit fixes your problem? I will cut a new release then.

**Comment by DasCapschen** [comment]
I just checked, and it works. Thank you very much :)

**Comment by Cito** [comment]
Glad to hear. Version 3.0.2 with the fix is now published.
