### ISSUE TITLE
Is there key difference with "databases" package?

### ISSUE THREAD

**Issue by david-shiko** [WebwareForPython/DBUtils#43]
Hi! I just looked for a connection pool manager and came across two similar packages: 
This one and "Databases" (https://github.com/encode/databases/). 
I am wondering if there is any key difference, apart from the async feature?

**Comment by Cito** [comment]
First time I hear about that package. It's much younger than DBUtils and the main focus seems to be asyncio support which DBUtils does not have (DBUtils was created long before that was a thing).
