### ISSUE TITLE
Customized connection parametrization

### ISSUE THREAD

**Issue by toximon** [WebwareForPython/DBUtils#45]
Hi, 

In some cases it is required to set additional parameters to a connection after it has been created. 
E.g. for pyodbc things like: con.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
I don't see any hints  in the documentation how to do this. 

regards, 
Anton.

**Comment by Cito** [comment]
Hi Anton.

There is no special support for that, and I think it's not needed since you can pass not only a DB API 2 compliant module, but also an arbitrary function for creating connections as "creator". So you can do something like this:

```python
from pyodbc import connect
from dbutils.pooled_db import PooledDB

def creator():
    con = connect('DRIVER={ODBC Driver 17 for SQL Server};'
                  'SERVER=localhost;DATABASE=testdb;UID=me;PWD=pass')
    con.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
    return con
    
db_pool = PooledDB(creator, mincached=5)
```

Would that work for you?

**Comment by toximon** [comment]
Hi Cito, 

thank you for the fast reply. 
i already tried to use a creator function which returns a pyodbc connection just like you describe. However different issues occur then: 
First: 
`'Could not determine failure exceptions (please set failures or creator.dbapi)'`

After i add  `PooledDB( ..., failures=pyodbc.Error)` to constructor's parameter list next error occur: 

`'Could not determine threadsafety (please set creator.dbapi or creator.threadsafety).'`

Then i stopped experimenting for this is obviously not how it is supposed to work.

Documentation states that one can pass creator function to PooledDB, but what i'm seeing from code and module behaviour is that an object is expected. 
Am i missing something?

Regards, 
Anton.

**Comment by Cito** [comment]
You can pass both, a function or an object (functions are objects anyway in Python).

Passing a function without attributes may not work if the underlying DB API module does not provide certain info on the connections. Then you need to pass the `dbapi` attribute as well. You can do it like this:

```python
from pyodbc import connect
from dbutils.pooled_db import PooledDB

def creator():
    con = connect('DRIVER={ODBC Driver 17 for SQL Server};'
                  'SERVER=localhost;DATABASE=testdb;UID=me;PWD=pass')
    con.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
    return con

creator.dbapi = pyodbc
creator.threadsafety = creator.dbapi.threadsafety

db_pool = PooledDB(creator, mincached=5)
```

**Comment by Cito** [comment]
Version 3.0.3 with these changes has now been released.
